#pragma once
// Generated by scripts/update_ziggurat_tables - do not edit

#include "monty/random/cuda_compatibility.hpp"

#ifndef MONTY_ZIGGURAT_REAL_TYPE
#define MONTY_ZIGGURAT_REAL_TYPE double
#endif

namespace monty {
namespace random {
namespace ziggurat {

CONSTANT
MONTY_ZIGGURAT_REAL_TYPE x[257] = {
{{x}}
};

CONSTANT
MONTY_ZIGGURAT_REAL_TYPE y[256] = {
{{y}}
};

}
}
}
