#pragma once
// Generated by scripts/update_ziggurat_tables - do not edit

#include "mcstate/random/cuda_compatibility.hpp"

#ifndef MCSTATE_ZIGGURAT_REAL_TYPE
#define MCSTATE_ZIGGURAT_REAL_TYPE double
#endif

namespace mcstate {
namespace random {
namespace ziggurat {

CONSTANT
MCSTATE_ZIGGURAT_REAL_TYPE x[257] = {
{{x}}
};

CONSTANT
MCSTATE_ZIGGURAT_REAL_TYPE y[256] = {
{{y}}
};

}
}
}
