// Generated by scripts/update_version - do not edit
#pragma once

#define MCSTATE_VERSION_MAJOR 0
#define MCSTATE_VERSION_MINOR 1
#define MCSTATE_VERSION_PATCH 0
#define MCSTATE_VERSION_STRING "0.1.0"
#define MCSTATE_VERSION_CODE 100
