#!/usr/bin/env Rscript
dsl_errors <- reside.utils::errors_parse(
  "vignettes/dsl-errors.Rmd", "E[0-9]{3}", "monty::monty_dsl_error_explain")
save(list = "dsl_errors", file = file.path("R/sysdata.rda"), version = 2)
