# Generated by cpp11: do not edit by hand

cpp_monty_rng_state <- function(ptr) {
  .Call(`_monty_cpp_monty_rng_state`, ptr)
}

cpp_monty_rng_set_state <- function(ptr, r_value) {
  invisible(.Call(`_monty_cpp_monty_rng_set_state`, ptr, r_value))
}

cpp_monty_rng_jump <- function(ptr, n) {
  invisible(.Call(`_monty_cpp_monty_rng_jump`, ptr, n))
}

cpp_monty_rng_long_jump <- function(ptr, n) {
  invisible(.Call(`_monty_cpp_monty_rng_long_jump`, ptr, n))
}

cpp_monty_random_real <- function(ptr) {
  .Call(`_monty_cpp_monty_random_real`, ptr)
}

cpp_monty_random_n_real <- function(n_samples, ptr) {
  .Call(`_monty_cpp_monty_random_n_real`, n_samples, ptr)
}

cpp_monty_random_exponential_rate <- function(rate, ptr) {
  .Call(`_monty_cpp_monty_random_exponential_rate`, rate, ptr)
}

cpp_monty_random_n_exponential_rate <- function(n_samples, rate, ptr) {
  .Call(`_monty_cpp_monty_random_n_exponential_rate`, n_samples, rate, ptr)
}

cpp_monty_random_exponential_mean <- function(mean, ptr) {
  .Call(`_monty_cpp_monty_random_exponential_mean`, mean, ptr)
}

cpp_monty_random_n_exponential_mean <- function(n_samples, mean, ptr) {
  .Call(`_monty_cpp_monty_random_n_exponential_mean`, n_samples, mean, ptr)
}

cpp_monty_random_poisson <- function(lambda, ptr) {
  .Call(`_monty_cpp_monty_random_poisson`, lambda, ptr)
}

cpp_monty_random_n_poisson <- function(n_samples, lambda, ptr) {
  .Call(`_monty_cpp_monty_random_n_poisson`, n_samples, lambda, ptr)
}

cpp_monty_random_beta <- function(a, b, ptr) {
  .Call(`_monty_cpp_monty_random_beta`, a, b, ptr)
}

cpp_monty_random_n_beta <- function(n_samples, a, b, ptr) {
  .Call(`_monty_cpp_monty_random_n_beta`, n_samples, a, b, ptr)
}

cpp_monty_random_binomial <- function(size, prob, ptr) {
  .Call(`_monty_cpp_monty_random_binomial`, size, prob, ptr)
}

cpp_monty_random_n_binomial <- function(n_samples, size, prob, ptr) {
  .Call(`_monty_cpp_monty_random_n_binomial`, n_samples, size, prob, ptr)
}

cpp_monty_random_cauchy <- function(location, scale, ptr) {
  .Call(`_monty_cpp_monty_random_cauchy`, location, scale, ptr)
}

cpp_monty_random_n_cauchy <- function(n_samples, location, scale, ptr) {
  .Call(`_monty_cpp_monty_random_n_cauchy`, n_samples, location, scale, ptr)
}

cpp_monty_random_gamma_scale <- function(shape, scale, ptr) {
  .Call(`_monty_cpp_monty_random_gamma_scale`, shape, scale, ptr)
}

cpp_monty_random_n_gamma_scale <- function(n_samples, shape, scale, ptr) {
  .Call(`_monty_cpp_monty_random_n_gamma_scale`, n_samples, shape, scale, ptr)
}

cpp_monty_random_gamma_rate <- function(shape, rate, ptr) {
  .Call(`_monty_cpp_monty_random_gamma_rate`, shape, rate, ptr)
}

cpp_monty_random_n_gamma_rate <- function(n_samples, shape, rate, ptr) {
  .Call(`_monty_cpp_monty_random_n_gamma_rate`, n_samples, shape, rate, ptr)
}

cpp_monty_random_negative_binomial_prob <- function(size, prob, ptr) {
  .Call(`_monty_cpp_monty_random_negative_binomial_prob`, size, prob, ptr)
}

cpp_monty_random_n_negative_binomial_prob <- function(n_samples, size, prob, ptr) {
  .Call(`_monty_cpp_monty_random_n_negative_binomial_prob`, n_samples, size, prob, ptr)
}

cpp_monty_random_negative_binomial_mu <- function(size, mu, ptr) {
  .Call(`_monty_cpp_monty_random_negative_binomial_mu`, size, mu, ptr)
}

cpp_monty_random_n_negative_binomial_mu <- function(n_samples, size, mu, ptr) {
  .Call(`_monty_cpp_monty_random_n_negative_binomial_mu`, n_samples, size, mu, ptr)
}

cpp_monty_random_normal <- function(mean, sd, ptr) {
  .Call(`_monty_cpp_monty_random_normal`, mean, sd, ptr)
}

cpp_monty_random_n_normal <- function(n_samples, mean, sd, ptr) {
  .Call(`_monty_cpp_monty_random_n_normal`, n_samples, mean, sd, ptr)
}

cpp_monty_random_uniform <- function(min, max, ptr) {
  .Call(`_monty_cpp_monty_random_uniform`, min, max, ptr)
}

cpp_monty_random_n_uniform <- function(n_samples, min, max, ptr) {
  .Call(`_monty_cpp_monty_random_n_uniform`, n_samples, min, max, ptr)
}

cpp_monty_random_log_normal <- function(meanlog, sdlog, ptr) {
  .Call(`_monty_cpp_monty_random_log_normal`, meanlog, sdlog, ptr)
}

cpp_monty_random_n_log_normal <- function(n_samples, meanlog, sdlog, ptr) {
  .Call(`_monty_cpp_monty_random_n_log_normal`, n_samples, meanlog, sdlog, ptr)
}

cpp_monty_random_beta_binomial_prob <- function(size, prob, rho, ptr) {
  .Call(`_monty_cpp_monty_random_beta_binomial_prob`, size, prob, rho, ptr)
}

cpp_monty_random_n_beta_binomial_prob <- function(n_samples, size, prob, rho, ptr) {
  .Call(`_monty_cpp_monty_random_n_beta_binomial_prob`, n_samples, size, prob, rho, ptr)
}

cpp_monty_random_beta_binomial_ab <- function(size, a, b, ptr) {
  .Call(`_monty_cpp_monty_random_beta_binomial_ab`, size, a, b, ptr)
}

cpp_monty_random_n_beta_binomial_ab <- function(n_samples, size, a, b, ptr) {
  .Call(`_monty_cpp_monty_random_n_beta_binomial_ab`, n_samples, size, a, b, ptr)
}

cpp_monty_random_hypergeometric <- function(n1, n2, k, ptr) {
  .Call(`_monty_cpp_monty_random_hypergeometric`, n1, n2, k, ptr)
}

cpp_monty_random_n_hypergeometric <- function(n_samples, n1, n2, k, ptr) {
  .Call(`_monty_cpp_monty_random_n_hypergeometric`, n_samples, n1, n2, k, ptr)
}

cpp_monty_random_truncated_normal <- function(mean, sd, min, max, ptr) {
  .Call(`_monty_cpp_monty_random_truncated_normal`, mean, sd, min, max, ptr)
}

cpp_monty_random_n_truncated_normal <- function(n_samples, mean, sd, min, max, ptr) {
  .Call(`_monty_cpp_monty_random_n_truncated_normal`, n_samples, mean, sd, min, max, ptr)
}

monty_rng_alloc <- function(r_seed, n_streams, deterministic) {
  .Call(`_monty_monty_rng_alloc`, r_seed, n_streams, deterministic)
}

monty_legacy_rng_jump <- function(ptr) {
  invisible(.Call(`_monty_monty_legacy_rng_jump`, ptr))
}

monty_legacy_rng_long_jump <- function(ptr) {
  invisible(.Call(`_monty_monty_legacy_rng_long_jump`, ptr))
}

monty_rng_random_real <- function(ptr, n, n_threads) {
  .Call(`_monty_monty_rng_random_real`, ptr, n, n_threads)
}

monty_rng_random_normal <- function(ptr, n, n_threads, algorithm) {
  .Call(`_monty_monty_rng_random_normal`, ptr, n, n_threads, algorithm)
}

monty_rng_uniform <- function(ptr, n, r_min, r_max, n_threads) {
  .Call(`_monty_monty_rng_uniform`, ptr, n, r_min, r_max, n_threads)
}

monty_rng_exponential_rate <- function(ptr, n, r_rate, n_threads) {
  .Call(`_monty_monty_rng_exponential_rate`, ptr, n, r_rate, n_threads)
}

monty_rng_exponential_mean <- function(ptr, n, r_mean, n_threads) {
  .Call(`_monty_monty_rng_exponential_mean`, ptr, n, r_mean, n_threads)
}

monty_rng_normal <- function(ptr, n, r_mean, r_sd, n_threads, algorithm) {
  .Call(`_monty_monty_rng_normal`, ptr, n, r_mean, r_sd, n_threads, algorithm)
}

monty_rng_binomial <- function(ptr, n, r_size, r_prob, n_threads) {
  .Call(`_monty_monty_rng_binomial`, ptr, n, r_size, r_prob, n_threads)
}

monty_rng_beta_binomial_ab <- function(ptr, n, r_size, r_a, r_b, n_threads) {
  .Call(`_monty_monty_rng_beta_binomial_ab`, ptr, n, r_size, r_a, r_b, n_threads)
}

monty_rng_beta_binomial_prob <- function(ptr, n, r_size, r_prob, r_rho, n_threads) {
  .Call(`_monty_monty_rng_beta_binomial_prob`, ptr, n, r_size, r_prob, r_rho, n_threads)
}

monty_rng_negative_binomial_prob <- function(ptr, n, r_size, r_prob, n_threads) {
  .Call(`_monty_monty_rng_negative_binomial_prob`, ptr, n, r_size, r_prob, n_threads)
}

monty_rng_negative_binomial_mu <- function(ptr, n, r_size, r_mu, n_threads) {
  .Call(`_monty_monty_rng_negative_binomial_mu`, ptr, n, r_size, r_mu, n_threads)
}

monty_rng_hypergeometric <- function(ptr, n, r_n1, r_n2, r_k, n_threads) {
  .Call(`_monty_monty_rng_hypergeometric`, ptr, n, r_n1, r_n2, r_k, n_threads)
}

monty_rng_gamma_scale <- function(ptr, n, r_shape, r_scale, n_threads) {
  .Call(`_monty_monty_rng_gamma_scale`, ptr, n, r_shape, r_scale, n_threads)
}

monty_rng_gamma_rate <- function(ptr, n, r_shape, r_rate, n_threads) {
  .Call(`_monty_monty_rng_gamma_rate`, ptr, n, r_shape, r_rate, n_threads)
}

monty_rng_poisson <- function(ptr, n, r_lambda, n_threads) {
  .Call(`_monty_monty_rng_poisson`, ptr, n, r_lambda, n_threads)
}

monty_rng_cauchy <- function(ptr, n, r_location, r_scale, n_threads) {
  .Call(`_monty_monty_rng_cauchy`, ptr, n, r_location, r_scale, n_threads)
}

monty_rng_beta <- function(ptr, n, r_a, r_b, n_threads) {
  .Call(`_monty_monty_rng_beta`, ptr, n, r_a, r_b, n_threads)
}

monty_rng_multinomial <- function(ptr, n, r_size, r_prob, n_threads) {
  .Call(`_monty_monty_rng_multinomial`, ptr, n, r_size, r_prob, n_threads)
}

monty_rng_truncated_normal <- function(ptr, n, r_mean, r_sd, r_min, r_max, n_threads) {
  .Call(`_monty_monty_rng_truncated_normal`, ptr, n, r_mean, r_sd, r_min, r_max, n_threads)
}

monty_legacy_rng_state <- function(ptr) {
  .Call(`_monty_monty_legacy_rng_state`, ptr)
}

monty_legacy_rng_set_state <- function(ptr, r_state) {
  invisible(.Call(`_monty_monty_legacy_rng_set_state`, ptr, r_state))
}

monty_rng_pointer_init <- function(n_streams, seed, long_jump, algorithm) {
  .Call(`_monty_monty_rng_pointer_init`, n_streams, seed, long_jump, algorithm)
}

monty_rng_pointer_sync <- function(obj, algorithm) {
  invisible(.Call(`_monty_monty_rng_pointer_sync`, obj, algorithm))
}

test_rng_pointer_get <- function(obj, n_streams) {
  .Call(`_monty_test_rng_pointer_get`, obj, n_streams)
}

test_xoshiro_run <- function(obj) {
  .Call(`_monty_test_xoshiro_run`, obj)
}
