# Generated by cpp11: do not edit by hand

mcstate_rng_alloc <- function(r_seed, n_streams, deterministic, is_float) {
  .Call(`_mcstate2_mcstate_rng_alloc`, r_seed, n_streams, deterministic, is_float)
}

mcstate_rng_jump <- function(ptr, is_float) {
  invisible(.Call(`_mcstate2_mcstate_rng_jump`, ptr, is_float))
}

mcstate_rng_long_jump <- function(ptr, is_float) {
  invisible(.Call(`_mcstate2_mcstate_rng_long_jump`, ptr, is_float))
}

mcstate_rng_random_real <- function(ptr, n, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_random_real`, ptr, n, n_threads, is_float)
}

mcstate_rng_random_normal <- function(ptr, n, n_threads, algorithm, is_float) {
  .Call(`_mcstate2_mcstate_rng_random_normal`, ptr, n, n_threads, algorithm, is_float)
}

mcstate_rng_uniform <- function(ptr, n, r_min, r_max, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_uniform`, ptr, n, r_min, r_max, n_threads, is_float)
}

mcstate_rng_exponential_rate <- function(ptr, n, r_rate, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_exponential_rate`, ptr, n, r_rate, n_threads, is_float)
}

mcstate_rng_exponential_mean <- function(ptr, n, r_mean, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_exponential_mean`, ptr, n, r_mean, n_threads, is_float)
}

mcstate_rng_normal <- function(ptr, n, r_mean, r_sd, n_threads, algorithm, is_float) {
  .Call(`_mcstate2_mcstate_rng_normal`, ptr, n, r_mean, r_sd, n_threads, algorithm, is_float)
}

mcstate_rng_binomial <- function(ptr, n, r_size, r_prob, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_binomial`, ptr, n, r_size, r_prob, n_threads, is_float)
}

mcstate_rng_nbinomial <- function(ptr, n, r_size, r_prob, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_nbinomial`, ptr, n, r_size, r_prob, n_threads, is_float)
}

mcstate_rng_hypergeometric <- function(ptr, n, r_n1, r_n2, r_k, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_hypergeometric`, ptr, n, r_n1, r_n2, r_k, n_threads, is_float)
}

mcstate_rng_gamma_scale <- function(ptr, n, r_shape, r_scale, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_gamma_scale`, ptr, n, r_shape, r_scale, n_threads, is_float)
}

mcstate_rng_gamma_rate <- function(ptr, n, r_shape, r_rate, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_gamma_rate`, ptr, n, r_shape, r_rate, n_threads, is_float)
}

mcstate_rng_poisson <- function(ptr, n, r_lambda, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_poisson`, ptr, n, r_lambda, n_threads, is_float)
}

mcstate_rng_cauchy <- function(ptr, n, r_location, r_scale, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_cauchy`, ptr, n, r_location, r_scale, n_threads, is_float)
}

mcstate_rng_beta <- function(ptr, n, r_a, r_b, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_beta`, ptr, n, r_a, r_b, n_threads, is_float)
}

mcstate_rng_multinomial <- function(ptr, n, r_size, r_prob, n_threads, is_float) {
  .Call(`_mcstate2_mcstate_rng_multinomial`, ptr, n, r_size, r_prob, n_threads, is_float)
}

mcstate_rng_state <- function(ptr, is_float) {
  .Call(`_mcstate2_mcstate_rng_state`, ptr, is_float)
}

mcstate_rng_pointer_init <- function(n_streams, seed, long_jump, algorithm) {
  .Call(`_mcstate2_mcstate_rng_pointer_init`, n_streams, seed, long_jump, algorithm)
}

mcstate_rng_pointer_sync <- function(obj, algorithm) {
  invisible(.Call(`_mcstate2_mcstate_rng_pointer_sync`, obj, algorithm))
}

test_rng_pointer_get <- function(obj, n_streams) {
  .Call(`_mcstate2_test_rng_pointer_get`, obj, n_streams)
}

test_xoshiro_run <- function(obj) {
  .Call(`_mcstate2_test_xoshiro_run`, obj)
}
